### ISSUE TITLE
[init] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by hwangsunwoong** [Team-Going/Going-Server#1]
## Issue 📌
프로젝트 초기 세팅

## Todo ✔️
- [x] Issue 템플릿 추가
- [x] PR 템플릿 추가
- [x] Label 생성
- [x] Branch Rule 설정
- [x] .gitignore 설정
- [x] 팀 AWS 계정 생성
- [x] 팀 Docker Hub 계정 생성
- [x] Docker 세팅
- [x] Docker-Compose 세팅
- [x] Redis 세팅
- [x] EC2 세팅
- [x] RDS 세팅
- [ ] S3 세팅
- [x] Nginx 세팅
- [x] 인프라 아키텍처 설계
- [x] Github Action CI/CD 세팅
- [x] 멀티 모듈 구조 분리
- [x] Readme 초안 작성
- [x] 디스코드 알림 연동
